version: '3'

services:
  postgres-pirate-manga:
    container_name: postgres-pirate-manga
    image: postgres:9.6
    restart: always
    networks:
      - pirate-manga-network
    ports:
      - '5432:5432'
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
  pirate-manga-server:
    depends_on:
      - postgres-pirate-manga
    container_name: pirate-manga-server
    hostname: pirate-manga-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/server
      - /server/node_modules
    ports:
      - '3000:3000'
    links:
      - postgres-pirate-manga
    restart: unless-stopped
    networks:
      - pirate-manga-network
    environment:
      - NPM_CONFIG_PRODUCTION=false
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Mexico_City
      - TZ=America/Mexico_City
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - pirate-manga-server
    networks:
      - pirate-manga-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email juancanche@pirate-manga.com --agree-tos --no-eff-email --force-renewal -d pirate-manga-server.gq  -d www.pirate-manga-server.gq

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ${WEB_ROOT_VOLUME_FOLDER}
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ${DHPARAM_VOLUME_FOLDER}
      o: bind
  node_modules:
    driver: local

networks:
  pirate-manga-network:
    driver: bridge